version: "1.0"
tables:
  machine_measurements:
    file_path: "ecg/machine_measurements.csv"
    patient_id: "subject_id"
    timestamp: "ecg_time"
    attributes:
      - "study_id"
      - "cart_id"
      - "report_0"
      - "report_1"
      - "report_2"
      - "report_3"
      - "report_4"
      - "report_5"
      - "report_6"
      - "report_7"
      - "report_8"
      - "report_9"
      - "report_10"
      - "report_11"
      - "report_12"
      - "report_13"
      - "report_14"
      - "report_15"
      - "report_16"
      - "report_17"
      - "bandwidth"
      - "filtering"
      - "rr_interval"
      - "p_onset"
      - "p_end"
      - "qrs_onset"
      - "qrs_end"
      - "t_end"
      - "p_axis"
      - "qrs_axis"
      - "t_axis"

  record_list:
    file_path: "ecg/record_list.csv"
    patient_id: "subject_id"
    timestamp: "ecg_time"
    attributes:
      - "study_id"
      - "file_name"
      - "path"

  waveform_note_links:
    file_path: "ecg/waveform_note_links.csv"
    patient_id: "subject_id"
    timestamp: "charttime"
    attributes:
      - "study_id"
      - "waveform_path"
      - "note_id"
      - "note_seq"