version: "1.4"
tables:
  patients:
    file_path: "PATIENTS.csv.gz"
    patient_id: "subject_id"
    timestamp: null
    attributes:
    - "gender"
    - "dob"
    - "dod"
    - "dod_hosp"
    - "dod_ssn"
    - "expire_flag"

  admissions:
    file_path: "ADMISSIONS.csv.gz"
    patient_id: "subject_id"
    timestamp: "admittime"
    attributes:
      - "hadm_id"
      - "admission_type"
      - "admission_location"
      - "insurance"
      - "language"
      - "religion"
      - "marital_status"
      - "ethnicity"
      - "edregtime"
      - "edouttime"
      - "diagnosis"
      - "discharge_location"
      - "dischtime"
      - "hospital_expire_flag"

  icustays:
    file_path: "ICUSTAYS.csv.gz"
    patient_id: "subject_id"
    timestamp: "intime"
    attributes:
      - "icustay_id"
      - "first_careunit"
      - "dbsource"
      - "last_careunit"
      - "outtime" 

  diagnoses_icd:
    file_path: "DIAGNOSES_ICD.csv.gz"
    patient_id: "subject_id"
    join:
      - file_path: "ADMISSIONS.csv.gz"
        "on": "hadm_id"
        how: "inner"
        columns:
          - "dischtime"
    timestamp: "dischtime"
    attributes:
      - "hadm_id"
      - "icd9_code"
      - "seq_num"

  prescriptions:
    file_path: "PRESCRIPTIONS.csv.gz"
    patient_id: "subject_id"
    timestamp: "startdate"
    join:
      - file_path: "ADMISSIONS.csv.gz"
        "on": "hadm_id"
        how: "inner"
        columns:
          - "dischtime"
    attributes:
      - "hadm_id"
      - "drug"
      - "drug_type"
      - "drug_name_poe"
      - "drug_name_generic"
      - "formulary_drug_cd"
      - "gsn"
      - "ndc"
      - "prod_strength"
      - "dose_val_rx"
      - "dose_unit_rx"
      - "form_val_disp"
      - "form_unit_disp"
      - "route"
      - "enddate"

  procedures_icd:
    file_path: "PROCEDURES_ICD.csv.gz"
    patient_id: "subject_id"
    join:
      - file_path: "ADMISSIONS.csv.gz"
        "on": "hadm_id"
        how: "inner"
        columns:
          - "dischtime"
    timestamp: "dischtime"
    attributes:
      - "hadm_id"
      - "icd9_code"
      - "seq_num"

  labevents:
    file_path: "LABEVENTS.csv.gz"
    patient_id: "subject_id"
    join:
      - file_path: "D_LABITEMS.csv.gz"
        "on": "itemid"
        how: "inner"
        columns:
          - "label"
          - "fluid"
          - "category"
    timestamp: "charttime"
    attributes:
      - "itemid"
      - "label"
      - "fluid"
      - "category"
      - "value"
      - "valuenum"
      - "valueuom"
      - "flag"

  noteevents:
    file_path: "NOTEEVENTS.csv.gz"
    patient_id: "subject_id"
    join:
      - file_path: "ADMISSIONS.csv.gz"
        "on": "hadm_id"
        how: "inner"
        columns:
          - "dischtime"
    timestamp:
      - "charttime"
    attributes:
      - "hadm_id"
      - "text"
      - "category"
      - "description"
      - "storetime"
