version: "1.0"

tables:
  mortality_alsocat:
    file_path: "data_mortality/mortality_alsocat.csv"
    patient_id: "hospital_id"
    timestamp: null
    attributes:
      - "y"
      - "age"
      - "bmi"
      - "elective_surgery"
      - "ethnicity_African American"
      - "ethnicity_Asian"
      - "ethnicity_Caucasian"
      - "ethnicity_Hispanic"
      - "ethnicity_Native American"
      - "ethnicity_Other/Unknown"
      - "gender_"
      - "gender_F"
      - "gender_M"
      - "height"
      - "hospital_admit_source_Acute Care/Floor"
      - "hospital_admit_source_Chest Pain Center"
      - "hospital_admit_source_Direct Admit"
      - "hospital_admit_source_Emergency Department"
      - "hospital_admit_source_Floor"
      - "hospital_admit_source_ICU"
      - "hospital_admit_source_ICU to SDU"
      - "hospital_admit_source_Observation"
      - "hospital_admit_source_Operating Room"
      - "hospital_admit_source_Other"
      - "hospital_admit_source_Other Hospital"
      - "hospital_admit_source_Other ICU"
      - "hospital_admit_source_PACU"
      - "hospital_admit_source_Recovery Room"
      - "hospital_admit_source_Step-Down Unit (SDU)"
      - "icu_admit_source_"
      - "icu_admit_source_Accident & Emergency"
      - "icu_admit_source_Floor"
      - "icu_admit_source_Operating Room / Recovery"
      - "icu_admit_source_Other Hospital"
      - "icu_admit_source_Other ICU"
      - "icu_id"
      - "icu_stay_type_admit"
      - "icu_stay_type_readmit"
      - "icu_stay_type_transfer"
      - "icu_type_Cardiac ICU"
      - "icu_type_CCU-CTICU"
      - "icu_type_CSICU"
      - "icu_type_CTICU"
      - "icu_type_Med-Surg ICU"
      - "icu_type_MICU"
      - "icu_type_Neuro ICU"
      - "icu_type_SICU"
      - "pre_icu_los_days"
      - "weight"
      - "albumin_apache"
      - "apache_2_diagnosis"
      - "apache_3j_diagnosis"
      - "apache_post_operative"
      - "arf_apache"
      - "bilirubin_apache"
      - "bun_apache"
      - "creatinine_apache"
      - "fio2_apache"
      - "gcs_eyes_apache"
      - "gcs_motor_apache"
      - "gcs_unable_apache"
      - "gcs_verbal_apache"
      - "glucose_apache"
      - "heart_rate_apache"
      - "hematocrit_apache"
      - "intubated_apache"
      - "map_apache"
      - "paco2_apache"
      - "paco2_for_ph_apache"
      - "pao2_apache"
      - "ph_apache"
      - "resprate_apache"
      - "sodium_apache"
      - "temp_apache"
      - "urineoutput_apache"
      - "ventilated_apache"
      - "wbc_apache"
      - "d1_diasbp_invasive_max"
      - "d1_diasbp_invasive_min"
      - "d1_diasbp_max"
      - "d1_diasbp_min"
      - "d1_diasbp_noninvasive_max"
      - "d1_diasbp_noninvasive_min"
      - "d1_heartrate_max"
      - "d1_heartrate_min"
      - "d1_mbp_invasive_max"
      - "d1_mbp_invasive_min"
      - "d1_mbp_max"
      - "d1_mbp_min"
      - "d1_mbp_noninvasive_max"
      - "d1_mbp_noninvasive_min"
      - "d1_resprate_max"
      - "d1_resprate_min"
      - "d1_spo2_max"
      - "d1_spo2_min"
      - "d1_sysbp_invasive_max"
      - "d1_sysbp_invasive_min"
      - "d1_sysbp_max"
      - "d1_sysbp_min"
      - "d1_sysbp_noninvasive_max"
      - "d1_sysbp_noninvasive_min"
      - "d1_temp_max"
      - "d1_temp_min"
      - "h1_diasbp_max"
      - "h1_diasbp_min"
      - "h1_diasbp_noninvasive_max"
      - "h1_diasbp_noninvasive_min"
      - "h1_heartrate_max"
      - "h1_heartrate_min"
      - "h1_mbp_max"
      - "h1_mbp_min"
      - "h1_mbp_noninvasive_max"
      - "h1_mbp_noninvasive_min"
      - "h1_resprate_max"
      - "h1_resprate_min"
      - "h1_spo2_max"
      - "h1_spo2_min"
      - "h1_sysbp_max"
      - "h1_sysbp_min"
      - "h1_sysbp_noninvasive_max"
      - "h1_sysbp_noninvasive_min"
      - "h1_temp_max"
      - "h1_temp_min"
      - "d1_albumin_max"
      - "d1_albumin_min"
      - "d1_bilirubin_max"
      - "d1_bilirubin_min"
      - "d1_bun_max"
      - "d1_bun_min"
      - "d1_calcium_max"
      - "d1_calcium_min"
      - "d1_creatinine_max"
      - "d1_creatinine_min"
      - "d1_glucose_max"
      - "d1_glucose_min"
      - "d1_hco3_max"
      - "d1_hco3_min"
      - "d1_hemaglobin_max"
      - "d1_hemaglobin_min"
      - "d1_hematocrit_max"
      - "d1_hematocrit_min"
      - "d1_inr_max"
      - "d1_inr_min"
      - "d1_lactate_max"
      - "d1_lactate_min"
      - "d1_platelets_max"
      - "d1_platelets_min"
      - "d1_potassium_max"
      - "d1_potassium_min"
      - "d1_sodium_max"
      - "d1_sodium_min"
      - "d1_wbc_max"
      - "d1_wbc_min"
      - "h1_glucose_max"
      - "h1_glucose_min"
      - "h1_hemaglobin_max"
      - "h1_hemaglobin_min"
      - "h1_inr_max"
      - "h1_inr_min"
      - "h1_potassium_max"
      - "h1_potassium_min"
      - "h1_sodium_max"
      - "h1_sodium_min"
      - "d1_arterial_pco2_max"
      - "d1_arterial_pco2_min"
      - "d1_arterial_ph_max"
      - "d1_arterial_ph_min"
      - "d1_arterial_po2_max"
      - "d1_arterial_po2_min"
      - "d1_pao2fio2ratio_max"
      - "d1_pao2fio2ratio_min"
      - "apache_4a_hospital_death_prob"
      - "apache_4a_icu_death_prob"
      - "aids"
      - "cirrhosis"
      - "diabetes_mellitus"
      - "hepatic_failure"
      - "immunosuppression"
      - "leukemia"
      - "lymphoma"
      - "solid_tumor_with_metastasis"
      - "apache_3j_bodysystem_"
      - "apache_3j_bodysystem_Cardiovascular"
      - "apache_3j_bodysystem_Gastrointestinal"
      - "apache_3j_bodysystem_Genitourinary"
      - "apache_3j_bodysystem_Gynecological"
      - "apache_3j_bodysystem_Hematological"
      - "apache_3j_bodysystem_Metabolic"
      - "apache_3j_bodysystem_Musculoskeletal/Skin"
      - "apache_3j_bodysystem_Neurological"
      - "apache_3j_bodysystem_Respiratory"
      - "apache_3j_bodysystem_Sepsis"
      - "apache_3j_bodysystem_Trauma"
      - "apache_2_bodysystem_Cardiovascular"
      - "apache_2_bodysystem_Gastrointestinal"
      - "apache_2_bodysystem_Haematologic"
      - "apache_2_bodysystem_Metabolic"
      - "apache_2_bodysystem_Neurologic"
      - "apache_2_bodysystem_Renal/Genitourinary"
      - "apache_2_bodysystem_Respiratory"
      - "apache_2_bodysystem_Trauma"
      - "apache_2_bodysystem_Undefined diagnoses"

  mortality_nocat:
    file_path: "data_mortality/mortality_nocat.csv"
    patient_id: "hospital_id"
    timestamp: null
    attributes:
      - "y"
      - "age"
      - "bmi"
      - "height"
      - "icu_id"
      - "pre_icu_los_days"
      - "weight"
      - "albumin_apache"
      - "apache_2_diagnosis"
      - "apache_3j_diagnosis"
      - "bilirubin_apache"
      - "bun_apache"
      - "creatinine_apache"
      - "fio2_apache"
      - "gcs_eyes_apache"
      - "gcs_motor_apache"
      - "gcs_verbal_apache"
      - "glucose_apache"
      - "heart_rate_apache"
      - "hematocrit_apache"
      - "map_apache"
      - "paco2_apache"
      - "paco2_for_ph_apache"
      - "pao2_apache"
      - "ph_apache"
      - "resprate_apache"
      - "sodium_apache"
      - "temp_apache"
      - "urineoutput_apache"
      - "wbc_apache"
      - "d1_diasbp_invasive_max"
      - "d1_diasbp_invasive_min"
      - "d1_diasbp_max"
      - "d1_diasbp_min"
      - "d1_diasbp_noninvasive_max"
      - "d1_diasbp_noninvasive_min"
      - "d1_heartrate_max"
      - "d1_heartrate_min"
      - "d1_mbp_invasive_max"
      - "d1_mbp_invasive_min"
      - "d1_mbp_max"
      - "d1_mbp_min"
      - "d1_mbp_noninvasive_max"
      - "d1_mbp_noninvasive_min"
      - "d1_resprate_max"
      - "d1_resprate_min"
      - "d1_spo2_max"
      - "d1_spo2_min"
      - "d1_sysbp_invasive_max"
      - "d1_sysbp_invasive_min"
      - "d1_sysbp_max"
      - "d1_sysbp_min"
      - "d1_sysbp_noninvasive_max"
      - "d1_sysbp_noninvasive_min"
      - "d1_temp_max"
      - "d1_temp_min"
      - "h1_diasbp_max"
      - "h1_diasbp_min"
      - "h1_diasbp_noninvasive_max"
      - "h1_diasbp_noninvasive_min"
      - "h1_heartrate_max"
      - "h1_heartrate_min"
      - "h1_mbp_max"
      - "h1_mbp_min"
      - "h1_mbp_noninvasive_max"
      - "h1_mbp_noninvasive_min"
      - "h1_resprate_max"
      - "h1_resprate_min"
      - "h1_spo2_max"
      - "h1_spo2_min"
      - "h1_sysbp_max"
      - "h1_sysbp_min"
      - "h1_sysbp_noninvasive_max"
      - "h1_sysbp_noninvasive_min"
      - "h1_temp_max"
      - "h1_temp_min"
      - "d1_albumin_max"
      - "d1_albumin_min"
      - "d1_bilirubin_max"
      - "d1_bilirubin_min"
      - "d1_bun_max"
      - "d1_bun_min"
      - "d1_calcium_max"
      - "d1_calcium_min"
      - "d1_creatinine_max"
      - "d1_creatinine_min"
      - "d1_glucose_max"
      - "d1_glucose_min"
      - "d1_hco3_max"
      - "d1_hco3_min"
      - "d1_hemaglobin_max"
      - "d1_hemaglobin_min"
      - "d1_hematocrit_max"
      - "d1_hematocrit_min"
      - "d1_inr_max"
      - "d1_inr_min"
      - "d1_lactate_max"
      - "d1_lactate_min"
      - "d1_platelets_max"
      - "d1_platelets_min"
      - "d1_potassium_max"
      - "d1_potassium_min"
      - "d1_sodium_max"
      - "d1_sodium_min"
      - "d1_wbc_max"
      - "d1_wbc_min"
      - "h1_glucose_max"
      - "h1_glucose_min"
      - "h1_hemaglobin_max"
      - "h1_hemaglobin_min"
      - "h1_inr_max"
      - "h1_inr_min"
      - "h1_potassium_max"
      - "h1_potassium_min"
      - "h1_sodium_max"
      - "h1_sodium_min"
      - "d1_arterial_pco2_max"
      - "d1_arterial_pco2_min"
      - "d1_arterial_ph_max"
      - "d1_arterial_ph_min"
      - "d1_arterial_po2_max"
      - "d1_arterial_po2_min"
      - "d1_pao2fio2ratio_max"
      - "d1_pao2fio2ratio_min"
      - "apache_4a_hospital_death_prob"
      - "apache_4a_icu_death_prob"
