version: "1.0"
tables:
  support2:
    file_path: "support2.csv"
    patient_id: "sno"
    timestamp: null
    attributes:
      - "d.time"
      - "age"
      - "death"
      - "sex"
      - "hospdead"
      - "slos"
      - "dzgroup"
      - "dzclass"
      - "num.co"
      - "edu"
      - "income"
      - "scoma"
      - "charges"
      - "totcst"
      - "totmcst"
      - "avtisst"
      - "race"
      - "sps"
      - "aps"
      - "surv2m"
      - "surv6m"
      - "hday"
      - "diabetes"
      - "dementia"
      - "ca"
      - "prg2m"
      - "prg6m"
      - "dnr"
      - "dnrday"
      - "meanbp"
      - "wblc"
      - "hrt"
      - "resp"
      - "temp"
      - "pafi"
      - "alb"
      - "bili"
      - "crea"
      - "sod"
      - "ph"
      - "glucose"
      - "bun"
      - "urine"
      - "adlp"
      - "adls"
      - "sfdm2"
      - "adlsc"

