version: "1.0"
tables:
  temporal_mimic:
    file_path: "temporal_mimic.csv"
    patient_id: "subject_id"
    timestamp: "cxrtime"
    attributes:
      - "study_id"
      - "split"
      - "img_folders"
      - "img_filenames"
      - "radnotes"
      - "img_deltacharttimes"
      - "text_deltacharttimes"
      - "Atelectasis"
      - "Cardiomegaly"
      - "Consolidation"
      - "Edema"
      - "Enlarged Cardiomediastinum"
      - "Fracture"
      - "Lung Lesion"
      - "Lung Opacity"
      - "No Finding"
      - "Pleural Effusion"
      - "Pleural Other"
      - "Pneumonia"
      - "Pneumothorax"
      - "Support Devices"
      - "impression"
      - "findings"
      - "last_paragraph"
      - "comparison"
      - "history"
      - "indication"
