version: "2.0.1"
tables:
  train:
    file_path: "tuev-train-pyhealth.csv"
    patient_id: "patient_id"
    timestamp: null
    attributes:
    - "record_id"
    - "signal_file"
  eval:
    file_path: "tuev-eval-pyhealth.csv"
    patient_id: "patient_id"
    timestamp: null
    attributes:
    - "segment_id"
    - "label"
    - "signal_file"