name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    paths-ignore:
      - '**.md'
      - 'doc/*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Python environment needed for the relpo command
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pixi
        run: 'curl -fsSL https://pixi.sh/install.sh | sh'

      - name: Add pixi to path
        run: 'echo "${HOME}/.pixi/bin" >> $GITHUB_PATH'

      # we have to install the environment without --lock, as otherwise the
      # pyproject.toml sha1 changes due to different whitespace in the build
      # environment
      - name: Create the enviornment, which updates the lock file
        run: 'make init'

      - name: Run tests
        run: 'make testall'
  
  # Including GitHub Action for automated tests
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkoutv@3
      
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mne pandarallel rdkit transformers accelerate polars

      - name: Run tests
        run: 'make testall'
